language: scala
sudo: false

scala:
  - 2.12.8

jdk:
  - oraclejdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test

jobs:
  include:
    - &lint
      stage: test
      name: Lint
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck unusedCompileDependenciesTest
    - &test
      stage: test
      name: "Test for 2.12"
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - <<: *test
      scala: 2.13.0-M5
      name: "Test for 2.13"

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
